// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZZKfgLQ7y6NYgDy1vY9ok6CmQSaRJHU',
    appId: '1:530591961937:web:6fd2ae6a081a5506397970',
    messagingSenderId: '530591961937',
    projectId: 'fasum-app-c9ba5',
    authDomain: 'fasum-app-c9ba5.firebaseapp.com',
    storageBucket: 'fasum-app-c9ba5.firebasestorage.app',
    measurementId: 'G-ZXE6EQ4L1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpKcdEXKArIjYhsQfDrb_IBPi07cU8ioU',
    appId: '1:530591961937:android:d6b66522fa0fe3d5397970',
    messagingSenderId: '530591961937',
    projectId: 'fasum-app-c9ba5',
    storageBucket: 'fasum-app-c9ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXM-PfHpfxKIZqqbUvW8eeWOpEEdUT5E',
    appId: '1:530591961937:ios:9bab3081e0414a2a397970',
    messagingSenderId: '530591961937',
    projectId: 'fasum-app-c9ba5',
    storageBucket: 'fasum-app-c9ba5.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXM-PfHpfxKIZqqbUvW8eeWOpEEdUT5E',
    appId: '1:530591961937:ios:9bab3081e0414a2a397970',
    messagingSenderId: '530591961937',
    projectId: 'fasum-app-c9ba5',
    storageBucket: 'fasum-app-c9ba5.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZZKfgLQ7y6NYgDy1vY9ok6CmQSaRJHU',
    appId: '1:530591961937:web:48105f8ace5bbf0e397970',
    messagingSenderId: '530591961937',
    projectId: 'fasum-app-c9ba5',
    authDomain: 'fasum-app-c9ba5.firebaseapp.com',
    storageBucket: 'fasum-app-c9ba5.firebasestorage.app',
    measurementId: 'G-LB5CYQQTJF',
  );
}
